'use strict';
// Renderer real e Excalidraw real. Ponte API inteiramente em memória, sem main de produção.
const {app,BrowserWindow,session,nativeImage}=require('electron');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {verifyServer,ORIGIN}=require('./qa-environment.cjs');
const run=path.resolve(__dirname,'../../artifacts/popups-qa-'+new Date().toISOString().replace(/[:.]/g,'-'));
fs.mkdirSync(run,{recursive:true});app.setPath('userData',path.join(run,'profile'));
app.commandLine.appendSwitch('disable-background-networking');app.commandLine.appendSwitch('disable-component-update');
const results=[],errors=[],blocked=[];let win,identity;app.on('window-all-closed',()=>{});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function bounded(promise,label){let timer;try{return await Promise.race([promise,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('Timeout20s: '+label)),20000))]);}finally{clearTimeout(timer);}}
const ev=code=>bounded(win.webContents.executeJavaScript(code),'evaluate '+code.slice(0,100));
async function until(code){for(let i=0;i<120;i++){if(await ev(code))return;await delay(100);}throw Error('Timeout: '+code);}
async function capture(name){console.log('STEP capture '+name);win.webContents.invalidate();await ev('document.fonts.ready.then(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))))');await delay(250);fs.writeFileSync(path.join(run,name+'.png'),(await bounded(win.webContents.capturePage(),'capturePage '+name)).toPNG());}
async function resize(width){win.setContentSize(width,900);await delay(160);await until('innerWidth==='+width);}
async function reset(){console.log('STEP reset');if(win&&!win.isDestroyed())win.destroy();win=new BrowserWindow({width:1440,height:960,show:false,title:'Cockpit — QA isolado de popups',webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,backgroundThrottling:false}});win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('render-process-gone',(_,d)=>errors.push('Renderer encerrou: '+d.reason));win.setContentSize(1440,900);await bounded(win.loadURL(ORIGIN+'/?cenario=supervisao&popupsqa=1'),'loadURL');console.log('STEP loaded');win.webContents.setZoomFactor(1);await until('!!window.__qa?.ready && __qa.panels?.length===3');await ev(`window.__pop={files:new Map(),seq:0};__qa.override('textoSalvar',async o=>{const p='C:/QA/'+(o.nome||('scene-'+(++__pop.seq)))+'.'+o.ext;__pop.files.set(p,{text:o.texto});return{arquivo:p};});__qa.override('textoLer',async o=>({content:__pop.files.get(o.arquivo)?.text}));__qa.override('imagemSalvar',async o=>{const p='C:/QA/image-'+(++__pop.seq)+'.png';__pop.files.set(p,{data:o.dados});return{arquivo:p};});__qa.override('anexoLer',async p=>{const a=__pop.files.get(p);return{path:p,nome:p.split('/').pop(),ext:p.split('.').pop(),bytes:a?.data?.length||a?.text?.length||10,...(a?.data?{mini:a.data}:{})};});__qa.override('verArquivo',async p=>({path:p,nome:p.split('/').pop(),tipo:'texto',dados:__pop.files.get(p)?.text||'QA'}));`);}
async function close(){await ev(`document.querySelectorAll('dialog[open]').forEach(d=>d.close());while(CockpitUI.layers.length)CockpitUI.closeLayer();fecharVisor();fecharModalGlobal();for(const p of panes.values())fecharModal(p);if(quadro)fecharQuadro();`);}
async function buttonText(text){await ev(`[...document.querySelectorAll('dialog[open] button')].find(b=>b.textContent===${JSON.stringify(text)})?.click();void 0`);}
async function check(name,fn){if(process.argv.includes('--health-layout')&&!name.startsWith('Diagnóstico'))return;console.log('STEP scenario '+name);await reset();console.log('STEP ready');try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.message,stack:e.stack});await capture('failure-'+results.length).catch(()=>{});}finally{const state=await ev('({errors:__qa.errors,missing:[...__qa.missing],engineCalls:__qa.calls.filter(c=>/^(paneStart|paneSend|approve|perguntaResponder|termRun)$/.test(c.method))})').catch(e=>({errors:[e.message]}));results.at(-1).state=state;if(state.errors?.length||state.missing?.length){results.at(-1).passed=false;}await close().catch(()=>{});}console.log(JSON.stringify(results.at(-1)));}
const search=async text=>{await ev(`document.querySelector('.ck-search').value=${JSON.stringify(text)};document.querySelector('.ck-search').dispatchEvent(new Event('input'));`);await delay(230);await until(`!document.querySelector('.ck-search-status').textContent.includes('Buscando')`);};
const groups=()=>ev(`[...document.querySelectorAll('.ck-result-group')].map(n=>n.textContent)`);
app.whenReady().then(async()=>{
 identity=await verifyServer();
 session.defaultSession.webRequest.onBeforeRequest((d,cb)=>{const allowed=d.url.startsWith(ORIGIN+'/')||d.url.startsWith('data:')||d.url.startsWith('blob:'+ORIGIN)||d.url==='about:blank';if(!allowed)blocked.push(d.url);cb({cancel:!allowed});});
 await check('Diagnóstico: três etapas verdadeiras, erro, tamanhos e gerenciador',async()=>{
  await ev(`irAoPainel(__qa.panel(__qa.panels[1]));__pop.health={itens:[{nome:'Confirmado',configurado:true,carregado:true,estado:'connected',ferramentas:3,ultimaChamada:{estado:'sucesso',quando:'2026-09-20T12:00:00Z',ferramenta:'listar'}},{nome:'Não configurado',configurado:false,carregado:false,estado:'notStarted'},{nome:'Sem confirmação',estado:'desconhecido'},{nome:'Chamada falhou',configurado:true,carregado:true,estado:'connected',ultimaChamada:{estado:'falhou',quando:'2026-09-20T12:00:00Z',erro:'ERRO_QA_VISIVEL',ferramenta:'ler'}}]};__qa.override('mcpDiagnostico',async()=>__pop.health);__qa.override('mcpRecarregar',async()=>({diagnostico:__pop.health,aviso:'RECARREGADO_QA'}));__qa.override('mcpList',async()=>[]);__qa.override('codexApps',async()=>({apps:[]}));CockpitCollaboration.health(focusPane);void 0`);
  await until("document.querySelectorAll('.co-health-card').length===4");
  assert.equal(await ev("document.querySelectorAll('.co-health-station').length"),12);
  const data=await ev("[...document.querySelectorAll('.co-health-card')].map(n=>({title:n.querySelector('h3').textContent,stages:[...n.querySelectorAll('.co-health-station')].map(s=>({label:s.getAttribute('aria-label'),cls:s.className}))}))");
  assert.match(data[1].stages[0].label,/: não$/);assert.match(data[2].stages[0].label,/não confirmado/);assert.match(data[3].stages[2].cls,/failed/);
  assert.ok(Math.abs(await ev("document.querySelector('.co-health-dialog').getBoundingClientRect().width")-640)<2);
  if(process.argv.includes('--health-probe')){
   const measure=()=>ev("(()=>{const d=document.querySelector('.co-health-dialog'),b=d.querySelector('.co-dialog-body');const g=n=>{const c=getComputedStyle(n),r=n.getBoundingClientRect();return{rect:{width:r.width,height:r.height,top:r.top,bottom:r.bottom},height:c.height,minHeight:c.minHeight,maxHeight:c.maxHeight,position:c.position,top:c.top,bottom:c.bottom,margin:c.margin,flex:c.flex,overflow:c.overflow};};return{dialog:g(d),body:g(b),children:[...d.children].map(g)}})()");
   const metrics={baseline:await measure()};await ev("document.querySelector('.co-health-dialog .co-dialog-body').style.flex='0 1 auto';void 0");metrics.flex=await measure();await capture('health-flex-probe');await ev("document.querySelector('.co-health-dialog').style.height='fit-content';void 0");metrics.fitContent=await measure();await capture('health-fit-content-probe');fs.writeFileSync(path.join(run,'health-measurements.json'),JSON.stringify(metrics,null,2));console.log(JSON.stringify(metrics));await ev("document.querySelector('.co-health-dialog').style.height='';document.querySelector('.co-health-dialog .co-dialog-body').style.flex='';void 0");
  }
  if(!process.argv.includes('--health-probe'))assert.ok(await ev("document.querySelector('.co-health-dialog').getBoundingClientRect().height")<650,'Health compacto ocupa menos de 650 px');
  await capture('health-1440');await buttonText('Recarregar conectores');await until("document.querySelector('.co-health').textContent.includes('RECARREGADO_QA')");
  await resize(600);assert.equal(await ev("document.querySelector('.co-health-dialog').scrollWidth<=document.querySelector('.co-health-dialog').clientWidth"),true);await capture('health-600');
  if(process.argv.includes('--health-layout')&&!process.argv.includes('--health-probe')){
   const measurements=[];
   const measure=label=>ev("(()=>{const d=document.querySelector('.co-health-dialog'),b=d.querySelector('.co-dialog-body'),f=d.querySelector('.co-actions'),r=d.getBoundingClientRect();return{label:"+JSON.stringify(label)+",width:r.width,height:r.height,top:r.top,bottom:r.bottom,bodyHeight:b.clientHeight,bodyScroll:b.scrollHeight,footerBottom:f.getBoundingClientRect().bottom}})()");
   measurements.push(await measure('compact-600'));assert.ok(measurements.at(-1).height<650,'Health compacto ocupa menos de 650 px');
   await ev("__pop.health.itens=Array.from({length:40},(_,i)=>({...__pop.health.itens[i%4],nome:'Conector '+(i+1)}));void 0");await buttonText('Atualizar diagnóstico');await until("document.querySelectorAll('.co-health-card').length===40");
   for(const width of [600,1440]){await resize(width);const m=await measure('long-'+width);measurements.push(m);assert.ok(m.height<=876.5);assert.ok(m.bodyScroll>m.bodyHeight);assert.ok(m.footerBottom<=889);await capture('health-long-'+width);}
   fs.writeFileSync(path.join(run,'health-layout.json'),JSON.stringify(measurements,null,2));
  }
  await buttonText('Gerenciar conectores');await until("!document.querySelector('dialog[open]') && !!focusPane.el.querySelector('.p-modal:not(.hidden)')");assert.match(await ev("focusPane.el.querySelector('.p-modal').textContent"),/Conectores/);await resize(1440);
 });
 await check('Debate: pronto, salvo, progresso real e conclusão no rascunho sem enviar',async()=>{
  await ev(`irAoPainel(__qa.panel(__qa.panels[1]));focusPane.busy=false;__qa.override('debateLeitura',async()=>({ampla:false}));__pop.debate={id:'qa-debate',paneId:focusPane.id,topic:'Decisão de teste',cwd:focusPane.cwd,leitura:true,rounds:2,status:'running',progress:{fala:2,total:4},messages:[{id:'m1',speaker:'codex',status:'completed',text:'Primeira avaliação',model:'gpt-6-astra',effort:'high'},{id:'m2',speaker:'claude',status:'running',text:'Avaliando',model:'claude-sonnet-5',effort:'high',startedAt:Date.now()}]};__qa.override('debateList',async()=>[__pop.debate]);__qa.override('debateGet',async()=>structuredClone(__pop.debate));focusPane.el.querySelector('.p-input').value='RASCUNHO_ORIGINAL';CockpitCollaboration.open(focusPane);void 0`);
  await until("!!document.querySelector('.co-salvos option[value=\"qa-debate\"]')");await capture('debate-ready-1440');
  await resize(600);assert.equal(await ev("document.querySelector('.co-debate-dialog').scrollWidth<=document.querySelector('.co-debate-dialog').clientWidth"),true);await capture('debate-ready-600');await resize(1440);
  await ev("document.querySelector('.co-salvos').value='qa-debate';document.querySelector('.co-salvos').dispatchEvent(new Event('change'));void 0");await until("document.querySelectorAll('.co-progress-step').length===4");
  assert.equal(await ev("document.querySelectorAll('.co-progress-step.completed').length"),1);assert.equal(await ev("document.querySelectorAll('.co-progress-step.running').length"),1);
  await ev("__pop.debate.status='completed';__pop.debate.messages[1].status='completed';__pop.debate.messages[1].text='Segunda avaliação';__pop.debate.messages.push({id:'m3',speaker:'codex',status:'completed',text:'Terceira avaliação'},{id:'m4',speaker:'claude',status:'completed',text:'CONCLUSAO_QA'});__qa.emit('onDebateEvent',__pop.debate);void 0");await until("document.querySelectorAll('.co-progress-step.completed').length===4");await capture('debate-completed-1440');
  await close();await ev('CockpitCollaboration.open(focusPane);void 0');await until("document.querySelector('.co-transcript')?.textContent.includes('CONCLUSAO_QA')");
  await buttonText('Levar conclusão para o campo');await until("!document.querySelector('dialog[open]')");const draft=await ev("focusPane.el.querySelector('.p-input').value");assert.match(draft,/^RASCUNHO_ORIGINAL/);assert.match(draft,/CONCLUSAO_QA/);assert.equal(await ev("__qa.calls.filter(c=>/^(paneSend|debateStart|debateContinue)$/.test(c.method)).length"),0);
 });
 await check('Quadro real: PNG e texto, rascunho, anexos, cena e confirmação de limpeza',async()=>{
  await ev(`irAoPainel(__qa.panel(__qa.panels[2]));focusPane.el.querySelector('.p-input').value='RASCUNHO_QUADRO';__pop.scene=[{type:'rectangle',id:'qa-entrada',x:100,y:100,width:180,height:80,label:{text:'Entrada'}},{type:'diamond',id:'qa-decisao',x:430,y:80,width:200,height:120,label:{text:'Aprovar?'}},{type:'arrow',id:'qa-ligacao',x:280,y:140,width:150,height:0,start:{id:'qa-entrada'},end:{id:'qa-decisao'}}];abrirQuadro(focusPane,JSON.stringify(__pop.scene));void 0`);
  await until("!!quadro?.q?.montado && !quadro.q.vazio() && !!document.querySelector('#quadroArea canvas')");
  assert.equal(await ev("typeof window.Quadro.versao.excalidraw"),'string');
  const count=await ev('quadro.q.api.getSceneElements().length');assert.ok(count>=3);await capture('quadro-1440');await resize(600);await capture('quadro-600');
  assert.equal(await ev("document.querySelector('#quadroPrompt').getBoundingClientRect().right<=innerWidth"),true);await resize(1440);
  await ev("document.querySelector('#quadroPrompt').click();void 0");await until("!quadro && focusPane.anexos.length===1 && focusPane.el.querySelector('.p-input').value.includes('Entrada')");
  const draft=await ev("focusPane.el.querySelector('.p-input').value");assert.match(draft,/^RASCUNHO_QUADRO/);assert.match(draft,/Aprovar/);
  const png=await ev("[...__pop.files.values()].find(v=>v.data)?.data");assert.match(png,/^data:image\/png;base64,/);const img=nativeImage.createFromDataURL(png);const dimensions=img.getSize();assert.ok(dimensions.width>200&&dimensions.height>100);fs.writeFileSync(path.join(run,'quadro-export-real.png'),img.toPNG());
  await ev("focusPane.el.querySelector('.p-anexos .anx-x').click();void 0");assert.equal(await ev('focusPane.anexos.length'),0);
  await ev('abrirQuadro(focusPane);void 0');await until('!!quadro?.q?.montado && !quadro.q.vazio()');assert.equal(await ev('quadro.q.api.getSceneElements().length'),count);
  await ev("document.querySelector('#quadroArquivo').click();void 0");await until("!quadro && focusPane.anexos.some(a=>a.ext==='excalidraw')");
  await ev('abrirQuadro(focusPane);void 0');await until('!!quadro?.q?.montado && !quadro.q.vazio()');await ev("__pop.confirmations=[];window.confirm=m=>{__pop.confirmations.push(m);return false;};document.querySelector('#quadroLimpar').click();void 0");assert.equal(await ev('quadro.q.vazio()'),false);assert.equal(await ev('__pop.confirmations.length'),1);
  await ev("window.confirm=m=>{__pop.confirmations.push(m);return true;};document.querySelector('#quadroLimpar').click();void 0");await until('quadro.q.vazio()');assert.equal(await ev('__pop.confirmations.length'),2);assert.equal(await ev("__qa.calls.filter(c=>c.method==='paneSend').length"),0);
 });
 await check('Busca: prefixos, grupos, pasta nova, home, Windows e resposta atrasada',async()=>{
  await ev(`__qa.override('listDir',async dir=>({entries:[{name:'NovaPasta',path:dir.replace(/[\\\\/]+$/,'')+'/NovaPasta',dir:true},{name:'arquivo.md',path:dir.replace(/[\\\\/]+$/,'')+'/arquivo.md',dir:false}]}));__qa.override('buscarArquivos',async o=>[{nome:o.termo+'.md',path:o.cwd+'/'+o.termo+'.md'}]);CockpitUI.palette();void 0`);
  assert.deepEqual(await groups(),['Agentes','Pastas','Comandos']);
  await search('>');assert.match(await ev("document.querySelector('.ck-search').getAttribute('aria-activedescendant')"),/-0$/);
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Down'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Down'});await delay(80);
  assert.match(await ev("document.querySelector('.ck-search').getAttribute('aria-activedescendant')"),/-1$/);
  win.webContents.sendInputEvent({type:'keyDown',keyCode:'Enter'});win.webContents.sendInputEvent({type:'keyUp',keyCode:'Enter'});await until("!!document.querySelector('#abNome')");await close();await ev('CockpitUI.palette();void 0');
  await search('@Codex');assert.deepEqual((await groups()).filter(g=>g!=='Conversas'),['Agentes']);/* guardadas viraram o grupo Conversas em 21/09 */assert.equal(await ev("__qa.calls.filter(c=>c.method==='buscarArquivos').length"),0);
  await search('>Terminal');assert.deepEqual(await groups(),['Comandos']);await capture('search-commands-1440');
  await search('/arquivo');assert.ok((await groups()).includes('Arquivos'));assert.equal((await groups()).includes('Agentes'),false);
  await search('~');assert.equal(await ev("__qa.calls.filter(c=>c.method==='listDir').at(-1).args[0]"),'C:/QA');
  await search('C:\\QA\\Nova');assert.equal(await ev("__qa.calls.filter(c=>c.method==='listDir').at(-1).args[0]"),'C:\\QA\\');await capture('search-windows-1440');
  const places=await ev('cfg.abas.length');await ev("[...document.querySelectorAll('.ck-result')].find(b=>b.textContent.includes('NovaPasta')).click();void 0");await until("!!document.querySelector('#abNome')");assert.match(await ev("document.querySelector('#abPastasLista').textContent"),/NovaPasta/);assert.equal(await ev('cfg.abas.length'),places);await close();
  await ev("CockpitUI.palette();__pop.pending={};__qa.override('listDir',async()=>({entries:[]}));__qa.override('buscarArquivos',o=>new Promise(resolve=>__pop.pending[o.termo]=resolve));void 0");
  await ev("document.querySelector('.ck-search').value='/antigo';document.querySelector('.ck-search').dispatchEvent(new Event('input'));");await until("!!__pop.pending.antigo");
  await ev("document.querySelector('.ck-search').value='/atual';document.querySelector('.ck-search').dispatchEvent(new Event('input'));");await until("!!__pop.pending.atual");await ev("__pop.pending.atual([{nome:'ATUAL_OK.md',path:'C:/QA/ATUAL_OK.md'}]);void 0");await until("document.querySelector('.ck-results').textContent.includes('ATUAL_OK')");await ev("__pop.pending.antigo([{nome:'ANTIGO_ERRO.md',path:'C:/QA/ANTIGO_ERRO.md'}]);void 0");await delay(150);assert.doesNotMatch(await ev("document.querySelector('.ck-results').textContent"),/ANTIGO_ERRO/);await resize(600);await capture('search-600');await resize(1440);
 });
 await check('Agente: catálogo por destino, falha de catálogo e capacidade de esforço',async()=>{
  await ev(`__pop.localModels=[{id:'modelo-local',nome:'Modelo Local QA',efforts:['low','high'],padrao:true}];__pop.remoteModels=[{id:'modelo-remoto',nome:'Modelo Remoto QA',efforts:['medium','max'],padrao:true}];__qa.override('codexModels',async remote=>remote?__pop.remoteModels:__pop.localModels);irAoPainel(__qa.panel(__qa.panels[1]));focusPane.started=false;focusPane.busy=false;focusPane.model='modelo-local';focusPane.effort='low';delete focusPane.uiCodexModels;CockpitUI.agentLayer(focusPane);void 0`);
  await until("document.querySelector('.ck-agent')?.textContent.includes('Modelo Local QA')");assert.equal(await ev("document.querySelectorAll('.ck-effort-level').length"),2);await capture('agent-local-1440');await close();
  await ev("__pop.localPane=focusPane;__pop.remotePane=newPane({engine:'codex',abaId:'qa-servidor',cwd:'/srv/projeto',model:'modelo-remoto'});__pop.remotePane.started=false;CockpitUI.agentLayer(__pop.remotePane);void 0");await until("document.querySelector('.ck-agent')?.textContent.includes('Modelo Remoto QA')");assert.doesNotMatch(await ev("document.querySelector('.ck-agent').textContent"),/Modelo Local QA/);assert.equal(await ev("__qa.calls.filter(c=>c.method==='codexModels').at(-1).args[0].host"),'servidor.example.invalid');await close();
  await ev("CockpitUI.agentLayer(__pop.localPane);void 0");await until("document.querySelector('.ck-agent')?.textContent.includes('Modelo Local QA')");await close();
  await ev("__qa.override('codexModels',async()=>[]);delete __pop.remotePane.uiCodexModels;MODELOS_CODEX=[];CockpitUI.agentLayer(__pop.remotePane);void 0");await until("document.querySelector('.ck-agent')?.textContent.includes('Catálogo indisponível')");assert.equal(await ev('__pop.remotePane.model'),'modelo-remoto');await capture('agent-empty-catalog');await close();
  for(const engine of ['gemini','grok','acp']){await ev(`__pop.capPane=newPane({engine:${JSON.stringify(engine)},abaId:'qa-produto',cwd:'C:/QA',model:''});CockpitUI.agentLayer(__pop.capPane);void 0`);await until("!!document.querySelector('.ck-mode-section')");assert.equal(await ev("document.querySelectorAll('.ck-effort-level,.ef-thumb').length"),0);await close();}
  await ev("CockpitUI.agentLayer(__pop.localPane);void 0");await until("document.querySelector('.ck-agent')?.textContent.includes('Modelo Local QA')");await resize(600);await capture('agent-600');assert.equal(await ev("document.querySelector('.ck-agent').scrollWidth<=document.querySelector('.ck-agent').clientWidth"),true);await resize(1440);
 });
 await check('Automações conserva atualização manual acessível',async()=>{await ev("CockpitUI.toolLayer('automations');void 0");await until("!!document.querySelector('.ck-automations-sheet')");assert.equal(await ev("document.querySelector('#btnRotinasAtualizar').getClientRects().length>0"),true);});
 const finalIdentity=await verifyServer();if(finalIdentity.sourceHash!==identity.sourceHash)errors.push('Fonte alterada durante a verificação');
 if(await ev('__qaIdentity.sourceHash')!==identity.sourceHash)errors.push('Página de outra revisão');
 if(blocked.length)errors.push('Pedidos externos bloqueados: '+blocked.join(', '));
 finish();
}).catch(error=>{errors.push(error.stack);finish();});
function finish(){const report={status:errors.length||results.some(r=>!r.passed)?'failed':'passed',at:new Date().toISOString(),sourceIdentity:identity,results,errors,blocked,authenticatedEnginesStarted:false,productionMainLoaded:false,run};fs.writeFileSync(path.join(run,'report.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.resolve(__dirname,'../../artifacts/popups-qa-atual.json'),JSON.stringify({run,status:report.status},null,2));console.log(JSON.stringify({run,status:report.status,errors,tests:results.map(r=>({name:r.name,passed:r.passed,error:r.error,state:r.state}))}));app.exit(report.status==='passed'?0:1);}
