const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (c) => ipcRenderer.invoke('config:set', c),
  home: () => ipcRenderer.invoke('sys:home'),
  plataforma: process.platform,

  pickFolder: (start) => ipcRenderer.invoke('dialog:pickFolder', start),
  listDir: (d) => ipcRenderer.invoke('fs:list', d),
  buscarArquivos: (o) => ipcRenderer.invoke('fs:buscarArquivos', o),
  gitStatus: (o) => ipcRenderer.invoke('git:status', o),
  gitDiff: (o) => ipcRenderer.invoke('git:diff', o),
  apagarSessao: (o) => ipcRenderer.invoke('sessao:apagar', o),
  exportarSessao: (o) => ipcRenderer.invoke('sessao:exportar', o),
  readFile: (f) => ipcRenderer.invoke('fs:read', f),
  openPath: (p) => ipcRenderer.invoke('shell:open', p),
  abrirLink: (u) => ipcRenderer.invoke('shell:link', u),
  openUrl: (u) => ipcRenderer.invoke('shell:openUrl', u),

  paneStart: (o) => ipcRenderer.invoke('pane:start', o),
  paneSend: (o) => ipcRenderer.invoke('pane:send', o),
  paneInterrupt: (o) => ipcRenderer.invoke('pane:interrupt', o),
  paneSteer: (o) => ipcRenderer.invoke('pane:steer', o),
  paneCompactar: (o) => ipcRenderer.invoke('pane:compactar', o),
  paneStop: (o) => ipcRenderer.invoke('pane:stop', o),
  approve: (o) => ipcRenderer.invoke('pane:approve', o),
  autoLiberar: (o) => ipcRenderer.invoke('pane:autoLiberar', o),
  liberacoes: (o) => ipcRenderer.invoke('pane:liberacoes', o),
  codexModels: () => ipcRenderer.invoke('codex:models'),
  sessionsClaude: (r) => ipcRenderer.invoke('sessions:claude', r),
  sessionsCodex: (r) => ipcRenderer.invoke('sessions:codex', r),
  sessionsClaudeRemoto: (o) => ipcRenderer.invoke('sessions:claudeRemoto', o),
  sessionHistoryRemoto: (o) => ipcRenderer.invoke('sessions:historyRemoto', o),
  sessionHistory: (o) => ipcRenderer.invoke('sessions:history', o),
  sessionTitulo: (o) => ipcRenderer.invoke('sessions:titulo', o),
  skills: (e) => ipcRenderer.invoke('skills:list', e),
  pickFiles: (k) => ipcRenderer.invoke('dialog:pickFiles', k),
  pickPhoto: () => ipcRenderer.invoke('user:pickPhoto'),
  anexoLer: (f) => ipcRenderer.invoke('anexo:ler', f),
  colados: () => ipcRenderer.invoke('clipboard:anexos'),
  verArquivo: (f) => ipcRenderer.invoke('arquivo:ver', f),
  renomear: (o) => ipcRenderer.invoke('sessao:renomear', o),
  buscarConversas: (o) => ipcRenderer.invoke('sessions:buscar', o),
  auth: (o) => ipcRenderer.invoke('auth:acao', o),
  contaLer: (e) => ipcRenderer.invoke('conta:ler', e),
  audioDisponivel: () => ipcRenderer.invoke('audio:disponivel'),
  audioTranscrever: (o) => ipcRenderer.invoke('audio:transcrever', o),
  audioAquecer: () => ipcRenderer.invoke('audio:aquecer'),
  contasListar: (e) => ipcRenderer.invoke('contas:listar', e),
  contasDisponivel: (e) => ipcRenderer.invoke('contas:disponivel', e),
  codexReiniciar: () => ipcRenderer.invoke('codex:reiniciar'),
  contasSalvar: (o) => ipcRenderer.invoke('contas:salvar', o),
  contasTrocar: (o) => ipcRenderer.invoke('contas:trocar', o),
  contasEsquecer: (o) => ipcRenderer.invoke('contas:esquecer', o),
  mcpList: (e) => ipcRenderer.invoke('mcp:list', e),
  mcpAcao: (o) => ipcRenderer.invoke('mcp:acao', o),

  termRun: (o) => ipcRenderer.invoke('term:run', o),
  termInput: (o) => ipcRenderer.invoke('term:input', o),
  termKill: (o) => ipcRenderer.invoke('term:kill', o),
  termResize: (o) => ipcRenderer.invoke('term:resize', o),
  onTermEvent: (cb) => ipcRenderer.on('term:event', (_e, p) => cb(p)),

  onPaneEvent: (cb) => ipcRenderer.on('pane:event', (_e, p) => cb(p)),
  onMenu: (cb) => ipcRenderer.on('menu', (_e, action) => cb(action)),
});
